services:
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc localhost 2181 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

  user-db:
    image: postgres
    restart: always
    shm_size: 128mb
    command: postgres -c max_prepared_transactions=10
    environment:
      POSTGRES_PASSWORD: sample_password
      POSTGRES_DB: user
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s

  order-db:
    image: postgres
    restart: always
    shm_size: 128mb
    command: postgres -c max_prepared_transactions=10
    environment:
      POSTGRES_PASSWORD: sample_password
      POSTGRES_DB: order
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      USER_SERVICE: user:8080
      ORDER_SERVICE: order:8081
      COORDINATOR_SERVICE: coordinator:8082

  coordinator:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    ports:
      - "8082:8082"
    environment:
      HOST: coordinator
      USER_SERVICE: user:8080
      ORDER_SERVICE: order:8081
      ZK_SERVER: zookeeper:2181
    depends_on:
      zookeeper:
        condition: service_healthy
        restart: true

  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    ports:
      - "8080:8080"
    environment:
      HOST: user
      ZK_SERVER: zookeeper:2181
    depends_on:
      user-db:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
        restart: true

  order:
    build:
      context: .
      dockerfile: order/Dockerfile
    ports:
      - "8081:8081"
    environment:
      HOST: order
      ZK_SERVER: zookeeper:2181
    depends_on:
      order-db:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
        restart: true