services:
  user-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: sample_password
      POSTGRES_DB: user
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s

  order-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: sample_password
      POSTGRES_DB: order
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      USER_SERVICE: user:8080
      ORDER_SERVICE: order:8081
      COORDINATOR_SERVICE: coordinator:8082

  coordinator:
    build: ./coordinator
    ports:
      - "8082:8082"
    environment:
      HOST: coordinator

  user:
    build: ./user
    ports:
      - "8080:8080"
    environment:
      HOST: user
    depends_on:
      user-db:
        condition: service_healthy

  order:
    build: ./order
    ports:
      - "8081:8081"
    environment:
      HOST: order
    depends_on:
      order-db:
        condition: service_healthy
